services:
  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - keydb
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: sh -c 'sleep 2 && python -m src.main'

  keydb:
    container_name: keydb
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - app_network


volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
